[package]
name = "api-books"
version = "0.1.0"
edition = "2021"


[dependencies]
graphul = "0.5.6"
dotenvy = "0.15.7"
serde = "1.0.164"
serde_json = "1.0.99"
diesel = { version = "2.1.0", features = ["postgres"] }
tokio = { version = "1.26.0", features = ["full"] }

